# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [bobcat, danij]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username Coke
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel -start
community_bridge: # Replace with a single Community Bridge project-name e.g., narwahls
liberapay: # Replace with a single Liberapay username cesar
issuehunt: # Replace with a single IssueHunt username Simba
otechie: # Replace with a single Otechie username Grrr
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://statefarm.com', 'htyps://forhims.com, https://1callms.com, https://goarmy.com, https://libertymutal.com']
